# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow helps you trigger a SonarCloud analysis of your code and populates
# GitHub Code Scanning alerts with the vulnerabilities found.
# Free for open source project.

# 1. Login to SonarCloud.io using your GitHub account

# 2. Import your project on SonarCloud
#     * Add your GitHub organization first, then add your repository as a new project.
#     * Please note that many languages are eligible for automatic analysis,
#       which means that the analysis will start automatically without the need to set up GitHub Actions.
#     * This behavior can be changed in Administration > Analysis Method.
#
# 3. Follow the SonarCloud in-product tutorial
#     * a. Copy/paste the Project Key and the Organization Key into the args parameter below
#          (You'll find this information in SonarCloud. Click on "Information" at the bottom left)
#
#     * b. Generate a new token and add it to your Github repository's secrets using the name SONAR_TOKEN
#          (On SonarCloud, click on your avatar on top-right > My account > Security
#           or go directly to https://sonarcloud.io/account/security/)

# Feel free to take a look at our documentation (https://docs.sonarcloud.io/getting-started/github/)
# or reach out to our community forum if you need some help (https://community.sonarsource.com/c/help/sc/9)

name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read  # дозволяє SonarCloud коментувати PR

jobs:
  sonar-check:
    name: SonarCloud Check
    runs-on: windows-latest   # рекомендується для .NET
    steps:
      # 1️⃣ Завантаження репозиторію
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # потрібно для коректного аналізу в SonarCloud

      # 2️⃣ Встановлення .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3️⃣ Встановлення інструментів Coverlet і SonarScanner
      - name: Install tools
        run: |
          dotnet tool install --global coverlet.console
          dotnet tool install --global dotnet-sonarscanner
          echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH
        shell: pwsh

      # 4️⃣ Ініціація сканування SonarCloud
      - name: SonarScanner Begin
        run: |
          dotnet sonarscanner begin `
            /k:"Rosarty_NetSdrClient1" `
            /o:"rosarty" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.cs.opencover.reportsPaths="NetSdrClientAppTests/TestResults/coverage.xml" `
            /d:sonar.exclusions=**/bin/**,**/obj/**,**/*.yml `
            /d:sonar.qualitygate.wait=true
        shell: pwsh

      # 5️⃣ Відновлення залежностей і збірка
      - name: Restore
        run: dotnet restore NetSdrClient.sln
        shell: pwsh

      - name: Build
        run: dotnet build NetSdrClient.sln -c Release --no-restore
        shell: pwsh

      # 6️⃣ Запуск тестів із покриттям
      - name: Run tests with coverage
        run: |
          dotnet test NetSdrClientAppTests/NetSdrClientAppTests.csproj `
            -c Release --no-build `
            /p:CollectCoverage=true `
            /p:CoverletOutput=TestResults/coverage.xml `
            /p:CoverletOutputFormat=opencover
        shell: pwsh

      # 7️⃣ Завершення сканування
      - name: SonarScanner End
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        shell: pwsh

      # 8️⃣ (опціонально) Завантаження звіту як артефакт
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: NetSdrClientAppTests/TestResults/coverage.xml
