# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow helps you trigger a SonarCloud analysis of your code and populates
# GitHub Code Scanning alerts with the vulnerabilities found.
# Free for open source project.

# 1. Login to SonarCloud.io using your GitHub account

# 2. Import your project on SonarCloud
#     * Add your GitHub organization first, then add your repository as a new project.
#     * Please note that many languages are eligible for automatic analysis,
#       which means that the analysis will start automatically without the need to set up GitHub Actions.
#     * This behavior can be changed in Administration > Analysis Method.
#
# 3. Follow the SonarCloud in-product tutorial
#     * a. Copy/paste the Project Key and the Organization Key into the args parameter below
#          (You'll find this information in SonarCloud. Click on "Information" at the bottom left)
#
#     * b. Generate a new token and add it to your Github repository's secrets using the name SONAR_TOKEN
#          (On SonarCloud, click on your avatar on top-right > My account > Security
#           or go directly to https://sonarcloud.io/account/security/)

# Feel free to take a look at our documentation (https://docs.sonarcloud.io/getting-started/github/)
# or reach out to our community forum if you need some help (https://community.sonarsource.com/c/help/sc/9)

name: .NET CI with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3) Install SonarScanner tool
      - name: Install SonarScanner
        shell: pwsh
        run: |
          dotnet tool install --global dotnet-sonarscanner
          $env:PATH += ";$env:USERPROFILE\.dotnet\tools"

      # 4) SonarScanner begin
      - name: SonarScanner Begin
        shell: pwsh
        run: |
          dotnet-sonarscanner begin `
            /k:"Rosarty_NetSdrClient1" `
            /o:"rosarty" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.cs.opencover.reportsPaths="**/coverage.xml" `
            /d:sonar.exclusions="**/bin/**,**/obj/**" `
            /d:sonar.qualitygate.wait=true

      # 5) Restore dependencies
      - name: Restore
        shell: pwsh
        run: dotnet restore NetSdrClient.sln

      # 6) Build project
      - name: Build
        shell: pwsh
        run: dotnet build NetSdrClient.sln -c Release --no-restore

      # 7) Run tests with coverage
      - name: Run tests with coverage
        shell: pwsh
        run: |
          dotnet test NetSdrClientAppTests/NetSdrClientAppTests.csproj -c Release --no-build `
            /p:CollectCoverage=true `
            /p:CoverletOutput=TestResults/coverage.xml `
            /p:CoverletOutputFormat=opencover

      # 8) SonarScanner end
      - name: SonarScanner End
        shell: pwsh
        run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
